### ISSUE TITLE
[Request] Add beta extension to Firefox

### ISSUE THREAD

**Issue by NickTheWilder** [SevenTV/ExtensionV3#65]
I currently use firefox and I'd love to beta test/bug find with the new development.

I previously posted a request here; https://github.com/SevenTV/Extension/issues/314. How ever the logs don't seem nearly as frequent in this new version, but I still think a settings modal would be beneficial similar to BTTV (if not already planned)

PS: I checked out the extension on chrome and it looks 10x better. 🎉

**Comment by Melonify** [comment]
The beta was approved on AMO yesterday, closing this issue.
