### ISSUE TITLE
Channel Picture is broken on emote menu

### ISSUE THREAD

**Issue by CycIoneTM** [SevenTV/ExtensionV3#68]
I'm sure you could care less since its only on the BTTV page but I figured I'd report it anyway.

https://user-images.githubusercontent.com/27637025/213325049-2ac2cb10-1cf9-44a2-970a-b59cf75ab2e4.mp4

**Comment by Excellify** [comment]
It uses the image provided by bttv's api. And if the person has not logged there for a long time it might have been deleted.

**Comment by CycIoneTM** [comment]
> It uses the image provided by bttv's api. And if the person has not logged there for a long time it might have been deleted.

Should there be a backup load to the twitch picture or something in this case?

**Comment by AnatoleAM** [comment]
It's because BTTV has old data about the user due to them not logging into their website for a long time. The profile picture they have stored is one that no longer exists
