### ISSUE TITLE
Login not working on 3.0.0.7000

### ISSUE THREAD

**Issue by niixxlegacy** [SevenTV/ExtensionV3#93]
Looks like the login callback don't work.
Sorry if not implemented yet, don't have the time to looks at sources sorry...
---
## Using
- Firefox 109.0.1 64bit
- Windows 11 22621.1105
- uBlock Origin 1.46.0 (Issue still there even if unloaded)

## Step to reproduce
- Install the beta addon
- Click on the settings button on the upper right corner in twitch (next to your profle picture).
- Click on 'Login' then 'Grant Permission' (Nothing happens except the button change for 'Login') then 'Login'
- (7tv.app opens in a window but nothing happens (already logged in or not))

**Comment by AnatoleAM** [comment]
Not implemented, track #87
