### ISSUE TITLE
7tv doesn't work on https://m.twitch.tv

### ISSUE THREAD

**Issue by MadDud** [SevenTV/ExtensionV3#99]
https://m.twitch.tv/forsen is a lightweight web version of twitch.tv, initially designed to be used on mobile browsers, however it's great for desktop browsers (Chrome) on old computers, because it doesn't consume too much ram (200MB vs 600MB in normal version). Surely not many people use the mobile wersion of twitch in a desktop browser, so this feature request wouldn't be used often.

7tv doesn't work on m.twitch.tv. 

Would it be possible to enable 7tv emotes for the mobile version?

**Comment by AnatoleAM** [comment]
After review, this site appears to be a completely different version of Twitch and has little relation to the main site. It also appears to have limited purpose as you cannot even chat there. This means an implementation would not be straightforward, and thus isn't being considered at this time. 

That doesn't rule out the possibility of someone making a pull request for it, however.
